sudo: required

language: generic

services:
  - docker

stages:
  - unit
  - e2e
  - e2e-optional


env:
  - SELENIUM_BROWSER=chrome
  - SELENIUM_BROWSER=firefox
  - SELENIUM_BROWSER=chrome DIST_SUB_PATH=nonmin
  - SELENIUM_BROWSER=firefox DIST_SUB_PATH=nonmin

jobs:
  include:
    - stage: unit
      before_script:
        - npm install
      script: npm run test-headless
    - stage: e2e
      before_script:
        - cd tests
        - docker-compose run --rm node npm run build
        - docker-compose up -d $SELENIUM_BROWSER
      script: docker-compose run --rm codeceptjs codeceptjs run-multiple basic:$SELENIUM_BROWSER --invert --grep  '@optional'
    - stage: e2e-optional
      before_script:
        - cd tests
        - docker-compose run --rm node npm run build
        - docker-compose up -d $SELENIUM_BROWSER
      script: docker-compose run --rm codeceptjs codeceptjs run-multiple basic:$SELENIUM_BROWSER --grep '@optional'
