sudo: required

language: generic

services:
  - docker

stages:
  - unit

env:
  - SELENIUM_BROWSER=chrome
  - SELENIUM_BROWSER=firefox
  - SELENIUM_BROWSER=chrome DIST_SUB_PATH=nonmin
  - SELENIUM_BROWSER=firefox DIST_SUB_PATH=nonmin

before_script:
  - npm install
  - cd tests
  - docker-compose run --rm node npm run build
  - docker-compose up -d $SELENIUM_BROWSER

#script: docker-compose run --rm codeceptjs codeceptjs run-multiple basic:$SELENIUM_BROWSER --invert --grep  '@optional'
script:
  - echo "skipping tests"
after_script:
  - docker-compose run --rm codeceptjs codeceptjs run-multiple basic:$SELENIUM_BROWSER --grep '@optional'

jobs:
  include:
    - stage: unit
      name: "Unit Tests"
      before_script:
        - npm install
      script: npm run test-headless
