sudo: required

language: generic

services:
  - docker

stages:
  - unit
  - test
  - optional

env:
  - SELENIUM_BROWSER=chrome
  - SELENIUM_BROWSER=firefox
  - SELENIUM_BROWSER=chrome DIST_SUB_PATH=nonmin
  - SELENIUM_BROWSER=firefox DIST_SUB_PATH=nonmin

matrix:
  allow_failures:
    - env: TEST_TYPE=optional

# default test stage

before_script: &before_script_reference
  - npm install
  - npm run test-headless # Run unit tests in headless chrome
  - cd tests
  - docker-compose run --rm node npm run build
  - docker-compose up -d $SELENIUM_BROWSER

script:
  - docker-compose ps
  - docker-compose run --rm codeceptjs codeceptjs run-multiple basic:$SELENIUM_BROWSER --invert --grep  '@optional'

jobs:
  include:

    - stage: unit
      name: "Unit"
      before_script:
        - npm install
      script: npm run test-headless

    - stage: optional
      name: "E2E Chrome Optional"
      env:
        - SELENIUM_BROWSER=chrome
        - TEST_TYPE=optional
      before_script: *before_script_reference
      script: docker-compose run --rm codeceptjs codeceptjs run-multiple basic:$SELENIUM_BROWSER --grep '@optional'

    - stage: optional
      name: "E2E Firefox Optional"
      env:
        - SELENIUM_BROWSER=firefox
        - TEST_TYPE=optional
      before_script: *before_script_reference
      script: docker-compose run --rm codeceptjs codeceptjs run-multiple basic:$SELENIUM_BROWSER --grep '@optional'
